package com.example.demo.model;

import java.math.BigDecimal;
import java.util.Date;

public class BondInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.id_
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.bond_code
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private String bondCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.bond_fullname
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private String bondFullname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.bond_kind
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private String bondKind;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.bond_shotname
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private String bondShotname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.sale_mode
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private String saleMode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.release_stat
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private String releaseStat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.bond_issuer
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private String bondIssuer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.sale_start_date
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private Date saleStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.sale_end_date
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private Date saleEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.value_date
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private Date valueDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.early_cash_date
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private Date earlyCashDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.early_int_date
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private Date earlyIntDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.pay_int_type
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private String payIntType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.bond_dura
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private Long bondDura;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.finish_date
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private Date finishDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.pay_int_freq
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private String payIntFreq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.int_calc_typee
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private String intCalcTypee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.stated_rate
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private BigDecimal statedRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.bond_unit
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private Long bondUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.cash_out_rate
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private BigDecimal cashOutRate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.basic_quota
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private Long basicQuota;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.product_id
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.liquidation_status
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private String liquidationStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.product_code
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private String productCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.bond_num
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private String bondNum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.bond_period
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private String bondPeriod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.cash_start_date
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private String cashStartDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.cash_end_date
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private String cashEndDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bond_info.stop_sale_sign
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    private byte[] stopSaleSign;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.id_
     *
     * @return the value of bond_info.id_
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.id_
     *
     * @param id the value for bond_info.id_
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.bond_code
     *
     * @return the value of bond_info.bond_code
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public String getBondCode() {
        return bondCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.bond_code
     *
     * @param bondCode the value for bond_info.bond_code
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setBondCode(String bondCode) {
        this.bondCode = bondCode == null ? null : bondCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.bond_fullname
     *
     * @return the value of bond_info.bond_fullname
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public String getBondFullname() {
        return bondFullname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.bond_fullname
     *
     * @param bondFullname the value for bond_info.bond_fullname
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setBondFullname(String bondFullname) {
        this.bondFullname = bondFullname == null ? null : bondFullname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.bond_kind
     *
     * @return the value of bond_info.bond_kind
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public String getBondKind() {
        return bondKind;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.bond_kind
     *
     * @param bondKind the value for bond_info.bond_kind
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setBondKind(String bondKind) {
        this.bondKind = bondKind == null ? null : bondKind.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.bond_shotname
     *
     * @return the value of bond_info.bond_shotname
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public String getBondShotname() {
        return bondShotname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.bond_shotname
     *
     * @param bondShotname the value for bond_info.bond_shotname
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setBondShotname(String bondShotname) {
        this.bondShotname = bondShotname == null ? null : bondShotname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.sale_mode
     *
     * @return the value of bond_info.sale_mode
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public String getSaleMode() {
        return saleMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.sale_mode
     *
     * @param saleMode the value for bond_info.sale_mode
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setSaleMode(String saleMode) {
        this.saleMode = saleMode == null ? null : saleMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.release_stat
     *
     * @return the value of bond_info.release_stat
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public String getReleaseStat() {
        return releaseStat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.release_stat
     *
     * @param releaseStat the value for bond_info.release_stat
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setReleaseStat(String releaseStat) {
        this.releaseStat = releaseStat == null ? null : releaseStat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.bond_issuer
     *
     * @return the value of bond_info.bond_issuer
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public String getBondIssuer() {
        return bondIssuer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.bond_issuer
     *
     * @param bondIssuer the value for bond_info.bond_issuer
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setBondIssuer(String bondIssuer) {
        this.bondIssuer = bondIssuer == null ? null : bondIssuer.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.sale_start_date
     *
     * @return the value of bond_info.sale_start_date
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public Date getSaleStartDate() {
        return saleStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.sale_start_date
     *
     * @param saleStartDate the value for bond_info.sale_start_date
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setSaleStartDate(Date saleStartDate) {
        this.saleStartDate = saleStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.sale_end_date
     *
     * @return the value of bond_info.sale_end_date
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public Date getSaleEndDate() {
        return saleEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.sale_end_date
     *
     * @param saleEndDate the value for bond_info.sale_end_date
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setSaleEndDate(Date saleEndDate) {
        this.saleEndDate = saleEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.value_date
     *
     * @return the value of bond_info.value_date
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public Date getValueDate() {
        return valueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.value_date
     *
     * @param valueDate the value for bond_info.value_date
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setValueDate(Date valueDate) {
        this.valueDate = valueDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.early_cash_date
     *
     * @return the value of bond_info.early_cash_date
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public Date getEarlyCashDate() {
        return earlyCashDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.early_cash_date
     *
     * @param earlyCashDate the value for bond_info.early_cash_date
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setEarlyCashDate(Date earlyCashDate) {
        this.earlyCashDate = earlyCashDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.early_int_date
     *
     * @return the value of bond_info.early_int_date
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public Date getEarlyIntDate() {
        return earlyIntDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.early_int_date
     *
     * @param earlyIntDate the value for bond_info.early_int_date
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setEarlyIntDate(Date earlyIntDate) {
        this.earlyIntDate = earlyIntDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.pay_int_type
     *
     * @return the value of bond_info.pay_int_type
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public String getPayIntType() {
        return payIntType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.pay_int_type
     *
     * @param payIntType the value for bond_info.pay_int_type
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setPayIntType(String payIntType) {
        this.payIntType = payIntType == null ? null : payIntType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.bond_dura
     *
     * @return the value of bond_info.bond_dura
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public Long getBondDura() {
        return bondDura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.bond_dura
     *
     * @param bondDura the value for bond_info.bond_dura
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setBondDura(Long bondDura) {
        this.bondDura = bondDura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.finish_date
     *
     * @return the value of bond_info.finish_date
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public Date getFinishDate() {
        return finishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.finish_date
     *
     * @param finishDate the value for bond_info.finish_date
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setFinishDate(Date finishDate) {
        this.finishDate = finishDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.pay_int_freq
     *
     * @return the value of bond_info.pay_int_freq
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public String getPayIntFreq() {
        return payIntFreq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.pay_int_freq
     *
     * @param payIntFreq the value for bond_info.pay_int_freq
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setPayIntFreq(String payIntFreq) {
        this.payIntFreq = payIntFreq == null ? null : payIntFreq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.int_calc_typee
     *
     * @return the value of bond_info.int_calc_typee
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public String getIntCalcTypee() {
        return intCalcTypee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.int_calc_typee
     *
     * @param intCalcTypee the value for bond_info.int_calc_typee
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setIntCalcTypee(String intCalcTypee) {
        this.intCalcTypee = intCalcTypee == null ? null : intCalcTypee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.stated_rate
     *
     * @return the value of bond_info.stated_rate
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public BigDecimal getStatedRate() {
        return statedRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.stated_rate
     *
     * @param statedRate the value for bond_info.stated_rate
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setStatedRate(BigDecimal statedRate) {
        this.statedRate = statedRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.bond_unit
     *
     * @return the value of bond_info.bond_unit
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public Long getBondUnit() {
        return bondUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.bond_unit
     *
     * @param bondUnit the value for bond_info.bond_unit
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setBondUnit(Long bondUnit) {
        this.bondUnit = bondUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.cash_out_rate
     *
     * @return the value of bond_info.cash_out_rate
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public BigDecimal getCashOutRate() {
        return cashOutRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.cash_out_rate
     *
     * @param cashOutRate the value for bond_info.cash_out_rate
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setCashOutRate(BigDecimal cashOutRate) {
        this.cashOutRate = cashOutRate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.basic_quota
     *
     * @return the value of bond_info.basic_quota
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public Long getBasicQuota() {
        return basicQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.basic_quota
     *
     * @param basicQuota the value for bond_info.basic_quota
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setBasicQuota(Long basicQuota) {
        this.basicQuota = basicQuota;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.product_id
     *
     * @return the value of bond_info.product_id
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.product_id
     *
     * @param productId the value for bond_info.product_id
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.liquidation_status
     *
     * @return the value of bond_info.liquidation_status
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public String getLiquidationStatus() {
        return liquidationStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.liquidation_status
     *
     * @param liquidationStatus the value for bond_info.liquidation_status
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setLiquidationStatus(String liquidationStatus) {
        this.liquidationStatus = liquidationStatus == null ? null : liquidationStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.product_code
     *
     * @return the value of bond_info.product_code
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public String getProductCode() {
        return productCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.product_code
     *
     * @param productCode the value for bond_info.product_code
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setProductCode(String productCode) {
        this.productCode = productCode == null ? null : productCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.bond_num
     *
     * @return the value of bond_info.bond_num
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public String getBondNum() {
        return bondNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.bond_num
     *
     * @param bondNum the value for bond_info.bond_num
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setBondNum(String bondNum) {
        this.bondNum = bondNum == null ? null : bondNum.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.bond_period
     *
     * @return the value of bond_info.bond_period
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public String getBondPeriod() {
        return bondPeriod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.bond_period
     *
     * @param bondPeriod the value for bond_info.bond_period
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setBondPeriod(String bondPeriod) {
        this.bondPeriod = bondPeriod == null ? null : bondPeriod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.cash_start_date
     *
     * @return the value of bond_info.cash_start_date
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public String getCashStartDate() {
        return cashStartDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.cash_start_date
     *
     * @param cashStartDate the value for bond_info.cash_start_date
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setCashStartDate(String cashStartDate) {
        this.cashStartDate = cashStartDate == null ? null : cashStartDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.cash_end_date
     *
     * @return the value of bond_info.cash_end_date
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public String getCashEndDate() {
        return cashEndDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.cash_end_date
     *
     * @param cashEndDate the value for bond_info.cash_end_date
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setCashEndDate(String cashEndDate) {
        this.cashEndDate = cashEndDate == null ? null : cashEndDate.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bond_info.stop_sale_sign
     *
     * @return the value of bond_info.stop_sale_sign
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public byte[] getStopSaleSign() {
        return stopSaleSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bond_info.stop_sale_sign
     *
     * @param stopSaleSign the value for bond_info.stop_sale_sign
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setStopSaleSign(byte[] stopSaleSign) {
        this.stopSaleSign = stopSaleSign;
    }
}