package com.example.demo.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class BondInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public BondInfoExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id_ is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id_ is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id_ =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id_ <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id_ >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id_ >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id_ <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id_ <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id_ in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id_ not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id_ between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id_ not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andBondCodeIsNull() {
            addCriterion("bond_code is null");
            return (Criteria) this;
        }

        public Criteria andBondCodeIsNotNull() {
            addCriterion("bond_code is not null");
            return (Criteria) this;
        }

        public Criteria andBondCodeEqualTo(String value) {
            addCriterion("bond_code =", value, "bondCode");
            return (Criteria) this;
        }

        public Criteria andBondCodeNotEqualTo(String value) {
            addCriterion("bond_code <>", value, "bondCode");
            return (Criteria) this;
        }

        public Criteria andBondCodeGreaterThan(String value) {
            addCriterion("bond_code >", value, "bondCode");
            return (Criteria) this;
        }

        public Criteria andBondCodeGreaterThanOrEqualTo(String value) {
            addCriterion("bond_code >=", value, "bondCode");
            return (Criteria) this;
        }

        public Criteria andBondCodeLessThan(String value) {
            addCriterion("bond_code <", value, "bondCode");
            return (Criteria) this;
        }

        public Criteria andBondCodeLessThanOrEqualTo(String value) {
            addCriterion("bond_code <=", value, "bondCode");
            return (Criteria) this;
        }

        public Criteria andBondCodeLike(String value) {
            addCriterion("bond_code like", value, "bondCode");
            return (Criteria) this;
        }

        public Criteria andBondCodeNotLike(String value) {
            addCriterion("bond_code not like", value, "bondCode");
            return (Criteria) this;
        }

        public Criteria andBondCodeIn(List<String> values) {
            addCriterion("bond_code in", values, "bondCode");
            return (Criteria) this;
        }

        public Criteria andBondCodeNotIn(List<String> values) {
            addCriterion("bond_code not in", values, "bondCode");
            return (Criteria) this;
        }

        public Criteria andBondCodeBetween(String value1, String value2) {
            addCriterion("bond_code between", value1, value2, "bondCode");
            return (Criteria) this;
        }

        public Criteria andBondCodeNotBetween(String value1, String value2) {
            addCriterion("bond_code not between", value1, value2, "bondCode");
            return (Criteria) this;
        }

        public Criteria andBondFullnameIsNull() {
            addCriterion("bond_fullname is null");
            return (Criteria) this;
        }

        public Criteria andBondFullnameIsNotNull() {
            addCriterion("bond_fullname is not null");
            return (Criteria) this;
        }

        public Criteria andBondFullnameEqualTo(String value) {
            addCriterion("bond_fullname =", value, "bondFullname");
            return (Criteria) this;
        }

        public Criteria andBondFullnameNotEqualTo(String value) {
            addCriterion("bond_fullname <>", value, "bondFullname");
            return (Criteria) this;
        }

        public Criteria andBondFullnameGreaterThan(String value) {
            addCriterion("bond_fullname >", value, "bondFullname");
            return (Criteria) this;
        }

        public Criteria andBondFullnameGreaterThanOrEqualTo(String value) {
            addCriterion("bond_fullname >=", value, "bondFullname");
            return (Criteria) this;
        }

        public Criteria andBondFullnameLessThan(String value) {
            addCriterion("bond_fullname <", value, "bondFullname");
            return (Criteria) this;
        }

        public Criteria andBondFullnameLessThanOrEqualTo(String value) {
            addCriterion("bond_fullname <=", value, "bondFullname");
            return (Criteria) this;
        }

        public Criteria andBondFullnameLike(String value) {
            addCriterion("bond_fullname like", value, "bondFullname");
            return (Criteria) this;
        }

        public Criteria andBondFullnameNotLike(String value) {
            addCriterion("bond_fullname not like", value, "bondFullname");
            return (Criteria) this;
        }

        public Criteria andBondFullnameIn(List<String> values) {
            addCriterion("bond_fullname in", values, "bondFullname");
            return (Criteria) this;
        }

        public Criteria andBondFullnameNotIn(List<String> values) {
            addCriterion("bond_fullname not in", values, "bondFullname");
            return (Criteria) this;
        }

        public Criteria andBondFullnameBetween(String value1, String value2) {
            addCriterion("bond_fullname between", value1, value2, "bondFullname");
            return (Criteria) this;
        }

        public Criteria andBondFullnameNotBetween(String value1, String value2) {
            addCriterion("bond_fullname not between", value1, value2, "bondFullname");
            return (Criteria) this;
        }

        public Criteria andBondKindIsNull() {
            addCriterion("bond_kind is null");
            return (Criteria) this;
        }

        public Criteria andBondKindIsNotNull() {
            addCriterion("bond_kind is not null");
            return (Criteria) this;
        }

        public Criteria andBondKindEqualTo(String value) {
            addCriterion("bond_kind =", value, "bondKind");
            return (Criteria) this;
        }

        public Criteria andBondKindNotEqualTo(String value) {
            addCriterion("bond_kind <>", value, "bondKind");
            return (Criteria) this;
        }

        public Criteria andBondKindGreaterThan(String value) {
            addCriterion("bond_kind >", value, "bondKind");
            return (Criteria) this;
        }

        public Criteria andBondKindGreaterThanOrEqualTo(String value) {
            addCriterion("bond_kind >=", value, "bondKind");
            return (Criteria) this;
        }

        public Criteria andBondKindLessThan(String value) {
            addCriterion("bond_kind <", value, "bondKind");
            return (Criteria) this;
        }

        public Criteria andBondKindLessThanOrEqualTo(String value) {
            addCriterion("bond_kind <=", value, "bondKind");
            return (Criteria) this;
        }

        public Criteria andBondKindLike(String value) {
            addCriterion("bond_kind like", value, "bondKind");
            return (Criteria) this;
        }

        public Criteria andBondKindNotLike(String value) {
            addCriterion("bond_kind not like", value, "bondKind");
            return (Criteria) this;
        }

        public Criteria andBondKindIn(List<String> values) {
            addCriterion("bond_kind in", values, "bondKind");
            return (Criteria) this;
        }

        public Criteria andBondKindNotIn(List<String> values) {
            addCriterion("bond_kind not in", values, "bondKind");
            return (Criteria) this;
        }

        public Criteria andBondKindBetween(String value1, String value2) {
            addCriterion("bond_kind between", value1, value2, "bondKind");
            return (Criteria) this;
        }

        public Criteria andBondKindNotBetween(String value1, String value2) {
            addCriterion("bond_kind not between", value1, value2, "bondKind");
            return (Criteria) this;
        }

        public Criteria andBondShotnameIsNull() {
            addCriterion("bond_shotname is null");
            return (Criteria) this;
        }

        public Criteria andBondShotnameIsNotNull() {
            addCriterion("bond_shotname is not null");
            return (Criteria) this;
        }

        public Criteria andBondShotnameEqualTo(String value) {
            addCriterion("bond_shotname =", value, "bondShotname");
            return (Criteria) this;
        }

        public Criteria andBondShotnameNotEqualTo(String value) {
            addCriterion("bond_shotname <>", value, "bondShotname");
            return (Criteria) this;
        }

        public Criteria andBondShotnameGreaterThan(String value) {
            addCriterion("bond_shotname >", value, "bondShotname");
            return (Criteria) this;
        }

        public Criteria andBondShotnameGreaterThanOrEqualTo(String value) {
            addCriterion("bond_shotname >=", value, "bondShotname");
            return (Criteria) this;
        }

        public Criteria andBondShotnameLessThan(String value) {
            addCriterion("bond_shotname <", value, "bondShotname");
            return (Criteria) this;
        }

        public Criteria andBondShotnameLessThanOrEqualTo(String value) {
            addCriterion("bond_shotname <=", value, "bondShotname");
            return (Criteria) this;
        }

        public Criteria andBondShotnameLike(String value) {
            addCriterion("bond_shotname like", value, "bondShotname");
            return (Criteria) this;
        }

        public Criteria andBondShotnameNotLike(String value) {
            addCriterion("bond_shotname not like", value, "bondShotname");
            return (Criteria) this;
        }

        public Criteria andBondShotnameIn(List<String> values) {
            addCriterion("bond_shotname in", values, "bondShotname");
            return (Criteria) this;
        }

        public Criteria andBondShotnameNotIn(List<String> values) {
            addCriterion("bond_shotname not in", values, "bondShotname");
            return (Criteria) this;
        }

        public Criteria andBondShotnameBetween(String value1, String value2) {
            addCriterion("bond_shotname between", value1, value2, "bondShotname");
            return (Criteria) this;
        }

        public Criteria andBondShotnameNotBetween(String value1, String value2) {
            addCriterion("bond_shotname not between", value1, value2, "bondShotname");
            return (Criteria) this;
        }

        public Criteria andSaleModeIsNull() {
            addCriterion("sale_mode is null");
            return (Criteria) this;
        }

        public Criteria andSaleModeIsNotNull() {
            addCriterion("sale_mode is not null");
            return (Criteria) this;
        }

        public Criteria andSaleModeEqualTo(String value) {
            addCriterion("sale_mode =", value, "saleMode");
            return (Criteria) this;
        }

        public Criteria andSaleModeNotEqualTo(String value) {
            addCriterion("sale_mode <>", value, "saleMode");
            return (Criteria) this;
        }

        public Criteria andSaleModeGreaterThan(String value) {
            addCriterion("sale_mode >", value, "saleMode");
            return (Criteria) this;
        }

        public Criteria andSaleModeGreaterThanOrEqualTo(String value) {
            addCriterion("sale_mode >=", value, "saleMode");
            return (Criteria) this;
        }

        public Criteria andSaleModeLessThan(String value) {
            addCriterion("sale_mode <", value, "saleMode");
            return (Criteria) this;
        }

        public Criteria andSaleModeLessThanOrEqualTo(String value) {
            addCriterion("sale_mode <=", value, "saleMode");
            return (Criteria) this;
        }

        public Criteria andSaleModeLike(String value) {
            addCriterion("sale_mode like", value, "saleMode");
            return (Criteria) this;
        }

        public Criteria andSaleModeNotLike(String value) {
            addCriterion("sale_mode not like", value, "saleMode");
            return (Criteria) this;
        }

        public Criteria andSaleModeIn(List<String> values) {
            addCriterion("sale_mode in", values, "saleMode");
            return (Criteria) this;
        }

        public Criteria andSaleModeNotIn(List<String> values) {
            addCriterion("sale_mode not in", values, "saleMode");
            return (Criteria) this;
        }

        public Criteria andSaleModeBetween(String value1, String value2) {
            addCriterion("sale_mode between", value1, value2, "saleMode");
            return (Criteria) this;
        }

        public Criteria andSaleModeNotBetween(String value1, String value2) {
            addCriterion("sale_mode not between", value1, value2, "saleMode");
            return (Criteria) this;
        }

        public Criteria andReleaseStatIsNull() {
            addCriterion("release_stat is null");
            return (Criteria) this;
        }

        public Criteria andReleaseStatIsNotNull() {
            addCriterion("release_stat is not null");
            return (Criteria) this;
        }

        public Criteria andReleaseStatEqualTo(String value) {
            addCriterion("release_stat =", value, "releaseStat");
            return (Criteria) this;
        }

        public Criteria andReleaseStatNotEqualTo(String value) {
            addCriterion("release_stat <>", value, "releaseStat");
            return (Criteria) this;
        }

        public Criteria andReleaseStatGreaterThan(String value) {
            addCriterion("release_stat >", value, "releaseStat");
            return (Criteria) this;
        }

        public Criteria andReleaseStatGreaterThanOrEqualTo(String value) {
            addCriterion("release_stat >=", value, "releaseStat");
            return (Criteria) this;
        }

        public Criteria andReleaseStatLessThan(String value) {
            addCriterion("release_stat <", value, "releaseStat");
            return (Criteria) this;
        }

        public Criteria andReleaseStatLessThanOrEqualTo(String value) {
            addCriterion("release_stat <=", value, "releaseStat");
            return (Criteria) this;
        }

        public Criteria andReleaseStatLike(String value) {
            addCriterion("release_stat like", value, "releaseStat");
            return (Criteria) this;
        }

        public Criteria andReleaseStatNotLike(String value) {
            addCriterion("release_stat not like", value, "releaseStat");
            return (Criteria) this;
        }

        public Criteria andReleaseStatIn(List<String> values) {
            addCriterion("release_stat in", values, "releaseStat");
            return (Criteria) this;
        }

        public Criteria andReleaseStatNotIn(List<String> values) {
            addCriterion("release_stat not in", values, "releaseStat");
            return (Criteria) this;
        }

        public Criteria andReleaseStatBetween(String value1, String value2) {
            addCriterion("release_stat between", value1, value2, "releaseStat");
            return (Criteria) this;
        }

        public Criteria andReleaseStatNotBetween(String value1, String value2) {
            addCriterion("release_stat not between", value1, value2, "releaseStat");
            return (Criteria) this;
        }

        public Criteria andBondIssuerIsNull() {
            addCriterion("bond_issuer is null");
            return (Criteria) this;
        }

        public Criteria andBondIssuerIsNotNull() {
            addCriterion("bond_issuer is not null");
            return (Criteria) this;
        }

        public Criteria andBondIssuerEqualTo(String value) {
            addCriterion("bond_issuer =", value, "bondIssuer");
            return (Criteria) this;
        }

        public Criteria andBondIssuerNotEqualTo(String value) {
            addCriterion("bond_issuer <>", value, "bondIssuer");
            return (Criteria) this;
        }

        public Criteria andBondIssuerGreaterThan(String value) {
            addCriterion("bond_issuer >", value, "bondIssuer");
            return (Criteria) this;
        }

        public Criteria andBondIssuerGreaterThanOrEqualTo(String value) {
            addCriterion("bond_issuer >=", value, "bondIssuer");
            return (Criteria) this;
        }

        public Criteria andBondIssuerLessThan(String value) {
            addCriterion("bond_issuer <", value, "bondIssuer");
            return (Criteria) this;
        }

        public Criteria andBondIssuerLessThanOrEqualTo(String value) {
            addCriterion("bond_issuer <=", value, "bondIssuer");
            return (Criteria) this;
        }

        public Criteria andBondIssuerLike(String value) {
            addCriterion("bond_issuer like", value, "bondIssuer");
            return (Criteria) this;
        }

        public Criteria andBondIssuerNotLike(String value) {
            addCriterion("bond_issuer not like", value, "bondIssuer");
            return (Criteria) this;
        }

        public Criteria andBondIssuerIn(List<String> values) {
            addCriterion("bond_issuer in", values, "bondIssuer");
            return (Criteria) this;
        }

        public Criteria andBondIssuerNotIn(List<String> values) {
            addCriterion("bond_issuer not in", values, "bondIssuer");
            return (Criteria) this;
        }

        public Criteria andBondIssuerBetween(String value1, String value2) {
            addCriterion("bond_issuer between", value1, value2, "bondIssuer");
            return (Criteria) this;
        }

        public Criteria andBondIssuerNotBetween(String value1, String value2) {
            addCriterion("bond_issuer not between", value1, value2, "bondIssuer");
            return (Criteria) this;
        }

        public Criteria andSaleStartDateIsNull() {
            addCriterion("sale_start_date is null");
            return (Criteria) this;
        }

        public Criteria andSaleStartDateIsNotNull() {
            addCriterion("sale_start_date is not null");
            return (Criteria) this;
        }

        public Criteria andSaleStartDateEqualTo(Date value) {
            addCriterionForJDBCDate("sale_start_date =", value, "saleStartDate");
            return (Criteria) this;
        }

        public Criteria andSaleStartDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("sale_start_date <>", value, "saleStartDate");
            return (Criteria) this;
        }

        public Criteria andSaleStartDateGreaterThan(Date value) {
            addCriterionForJDBCDate("sale_start_date >", value, "saleStartDate");
            return (Criteria) this;
        }

        public Criteria andSaleStartDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("sale_start_date >=", value, "saleStartDate");
            return (Criteria) this;
        }

        public Criteria andSaleStartDateLessThan(Date value) {
            addCriterionForJDBCDate("sale_start_date <", value, "saleStartDate");
            return (Criteria) this;
        }

        public Criteria andSaleStartDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("sale_start_date <=", value, "saleStartDate");
            return (Criteria) this;
        }

        public Criteria andSaleStartDateIn(List<Date> values) {
            addCriterionForJDBCDate("sale_start_date in", values, "saleStartDate");
            return (Criteria) this;
        }

        public Criteria andSaleStartDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("sale_start_date not in", values, "saleStartDate");
            return (Criteria) this;
        }

        public Criteria andSaleStartDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("sale_start_date between", value1, value2, "saleStartDate");
            return (Criteria) this;
        }

        public Criteria andSaleStartDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("sale_start_date not between", value1, value2, "saleStartDate");
            return (Criteria) this;
        }

        public Criteria andSaleEndDateIsNull() {
            addCriterion("sale_end_date is null");
            return (Criteria) this;
        }

        public Criteria andSaleEndDateIsNotNull() {
            addCriterion("sale_end_date is not null");
            return (Criteria) this;
        }

        public Criteria andSaleEndDateEqualTo(Date value) {
            addCriterionForJDBCDate("sale_end_date =", value, "saleEndDate");
            return (Criteria) this;
        }

        public Criteria andSaleEndDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("sale_end_date <>", value, "saleEndDate");
            return (Criteria) this;
        }

        public Criteria andSaleEndDateGreaterThan(Date value) {
            addCriterionForJDBCDate("sale_end_date >", value, "saleEndDate");
            return (Criteria) this;
        }

        public Criteria andSaleEndDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("sale_end_date >=", value, "saleEndDate");
            return (Criteria) this;
        }

        public Criteria andSaleEndDateLessThan(Date value) {
            addCriterionForJDBCDate("sale_end_date <", value, "saleEndDate");
            return (Criteria) this;
        }

        public Criteria andSaleEndDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("sale_end_date <=", value, "saleEndDate");
            return (Criteria) this;
        }

        public Criteria andSaleEndDateIn(List<Date> values) {
            addCriterionForJDBCDate("sale_end_date in", values, "saleEndDate");
            return (Criteria) this;
        }

        public Criteria andSaleEndDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("sale_end_date not in", values, "saleEndDate");
            return (Criteria) this;
        }

        public Criteria andSaleEndDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("sale_end_date between", value1, value2, "saleEndDate");
            return (Criteria) this;
        }

        public Criteria andSaleEndDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("sale_end_date not between", value1, value2, "saleEndDate");
            return (Criteria) this;
        }

        public Criteria andValueDateIsNull() {
            addCriterion("value_date is null");
            return (Criteria) this;
        }

        public Criteria andValueDateIsNotNull() {
            addCriterion("value_date is not null");
            return (Criteria) this;
        }

        public Criteria andValueDateEqualTo(Date value) {
            addCriterionForJDBCDate("value_date =", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("value_date <>", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateGreaterThan(Date value) {
            addCriterionForJDBCDate("value_date >", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("value_date >=", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateLessThan(Date value) {
            addCriterionForJDBCDate("value_date <", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("value_date <=", value, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateIn(List<Date> values) {
            addCriterionForJDBCDate("value_date in", values, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("value_date not in", values, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("value_date between", value1, value2, "valueDate");
            return (Criteria) this;
        }

        public Criteria andValueDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("value_date not between", value1, value2, "valueDate");
            return (Criteria) this;
        }

        public Criteria andEarlyCashDateIsNull() {
            addCriterion("early_cash_date is null");
            return (Criteria) this;
        }

        public Criteria andEarlyCashDateIsNotNull() {
            addCriterion("early_cash_date is not null");
            return (Criteria) this;
        }

        public Criteria andEarlyCashDateEqualTo(Date value) {
            addCriterionForJDBCDate("early_cash_date =", value, "earlyCashDate");
            return (Criteria) this;
        }

        public Criteria andEarlyCashDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("early_cash_date <>", value, "earlyCashDate");
            return (Criteria) this;
        }

        public Criteria andEarlyCashDateGreaterThan(Date value) {
            addCriterionForJDBCDate("early_cash_date >", value, "earlyCashDate");
            return (Criteria) this;
        }

        public Criteria andEarlyCashDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("early_cash_date >=", value, "earlyCashDate");
            return (Criteria) this;
        }

        public Criteria andEarlyCashDateLessThan(Date value) {
            addCriterionForJDBCDate("early_cash_date <", value, "earlyCashDate");
            return (Criteria) this;
        }

        public Criteria andEarlyCashDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("early_cash_date <=", value, "earlyCashDate");
            return (Criteria) this;
        }

        public Criteria andEarlyCashDateIn(List<Date> values) {
            addCriterionForJDBCDate("early_cash_date in", values, "earlyCashDate");
            return (Criteria) this;
        }

        public Criteria andEarlyCashDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("early_cash_date not in", values, "earlyCashDate");
            return (Criteria) this;
        }

        public Criteria andEarlyCashDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("early_cash_date between", value1, value2, "earlyCashDate");
            return (Criteria) this;
        }

        public Criteria andEarlyCashDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("early_cash_date not between", value1, value2, "earlyCashDate");
            return (Criteria) this;
        }

        public Criteria andEarlyIntDateIsNull() {
            addCriterion("early_int_date is null");
            return (Criteria) this;
        }

        public Criteria andEarlyIntDateIsNotNull() {
            addCriterion("early_int_date is not null");
            return (Criteria) this;
        }

        public Criteria andEarlyIntDateEqualTo(Date value) {
            addCriterionForJDBCDate("early_int_date =", value, "earlyIntDate");
            return (Criteria) this;
        }

        public Criteria andEarlyIntDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("early_int_date <>", value, "earlyIntDate");
            return (Criteria) this;
        }

        public Criteria andEarlyIntDateGreaterThan(Date value) {
            addCriterionForJDBCDate("early_int_date >", value, "earlyIntDate");
            return (Criteria) this;
        }

        public Criteria andEarlyIntDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("early_int_date >=", value, "earlyIntDate");
            return (Criteria) this;
        }

        public Criteria andEarlyIntDateLessThan(Date value) {
            addCriterionForJDBCDate("early_int_date <", value, "earlyIntDate");
            return (Criteria) this;
        }

        public Criteria andEarlyIntDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("early_int_date <=", value, "earlyIntDate");
            return (Criteria) this;
        }

        public Criteria andEarlyIntDateIn(List<Date> values) {
            addCriterionForJDBCDate("early_int_date in", values, "earlyIntDate");
            return (Criteria) this;
        }

        public Criteria andEarlyIntDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("early_int_date not in", values, "earlyIntDate");
            return (Criteria) this;
        }

        public Criteria andEarlyIntDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("early_int_date between", value1, value2, "earlyIntDate");
            return (Criteria) this;
        }

        public Criteria andEarlyIntDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("early_int_date not between", value1, value2, "earlyIntDate");
            return (Criteria) this;
        }

        public Criteria andPayIntTypeIsNull() {
            addCriterion("pay_int_type is null");
            return (Criteria) this;
        }

        public Criteria andPayIntTypeIsNotNull() {
            addCriterion("pay_int_type is not null");
            return (Criteria) this;
        }

        public Criteria andPayIntTypeEqualTo(String value) {
            addCriterion("pay_int_type =", value, "payIntType");
            return (Criteria) this;
        }

        public Criteria andPayIntTypeNotEqualTo(String value) {
            addCriterion("pay_int_type <>", value, "payIntType");
            return (Criteria) this;
        }

        public Criteria andPayIntTypeGreaterThan(String value) {
            addCriterion("pay_int_type >", value, "payIntType");
            return (Criteria) this;
        }

        public Criteria andPayIntTypeGreaterThanOrEqualTo(String value) {
            addCriterion("pay_int_type >=", value, "payIntType");
            return (Criteria) this;
        }

        public Criteria andPayIntTypeLessThan(String value) {
            addCriterion("pay_int_type <", value, "payIntType");
            return (Criteria) this;
        }

        public Criteria andPayIntTypeLessThanOrEqualTo(String value) {
            addCriterion("pay_int_type <=", value, "payIntType");
            return (Criteria) this;
        }

        public Criteria andPayIntTypeLike(String value) {
            addCriterion("pay_int_type like", value, "payIntType");
            return (Criteria) this;
        }

        public Criteria andPayIntTypeNotLike(String value) {
            addCriterion("pay_int_type not like", value, "payIntType");
            return (Criteria) this;
        }

        public Criteria andPayIntTypeIn(List<String> values) {
            addCriterion("pay_int_type in", values, "payIntType");
            return (Criteria) this;
        }

        public Criteria andPayIntTypeNotIn(List<String> values) {
            addCriterion("pay_int_type not in", values, "payIntType");
            return (Criteria) this;
        }

        public Criteria andPayIntTypeBetween(String value1, String value2) {
            addCriterion("pay_int_type between", value1, value2, "payIntType");
            return (Criteria) this;
        }

        public Criteria andPayIntTypeNotBetween(String value1, String value2) {
            addCriterion("pay_int_type not between", value1, value2, "payIntType");
            return (Criteria) this;
        }

        public Criteria andBondDuraIsNull() {
            addCriterion("bond_dura is null");
            return (Criteria) this;
        }

        public Criteria andBondDuraIsNotNull() {
            addCriterion("bond_dura is not null");
            return (Criteria) this;
        }

        public Criteria andBondDuraEqualTo(Long value) {
            addCriterion("bond_dura =", value, "bondDura");
            return (Criteria) this;
        }

        public Criteria andBondDuraNotEqualTo(Long value) {
            addCriterion("bond_dura <>", value, "bondDura");
            return (Criteria) this;
        }

        public Criteria andBondDuraGreaterThan(Long value) {
            addCriterion("bond_dura >", value, "bondDura");
            return (Criteria) this;
        }

        public Criteria andBondDuraGreaterThanOrEqualTo(Long value) {
            addCriterion("bond_dura >=", value, "bondDura");
            return (Criteria) this;
        }

        public Criteria andBondDuraLessThan(Long value) {
            addCriterion("bond_dura <", value, "bondDura");
            return (Criteria) this;
        }

        public Criteria andBondDuraLessThanOrEqualTo(Long value) {
            addCriterion("bond_dura <=", value, "bondDura");
            return (Criteria) this;
        }

        public Criteria andBondDuraIn(List<Long> values) {
            addCriterion("bond_dura in", values, "bondDura");
            return (Criteria) this;
        }

        public Criteria andBondDuraNotIn(List<Long> values) {
            addCriterion("bond_dura not in", values, "bondDura");
            return (Criteria) this;
        }

        public Criteria andBondDuraBetween(Long value1, Long value2) {
            addCriterion("bond_dura between", value1, value2, "bondDura");
            return (Criteria) this;
        }

        public Criteria andBondDuraNotBetween(Long value1, Long value2) {
            addCriterion("bond_dura not between", value1, value2, "bondDura");
            return (Criteria) this;
        }

        public Criteria andFinishDateIsNull() {
            addCriterion("finish_date is null");
            return (Criteria) this;
        }

        public Criteria andFinishDateIsNotNull() {
            addCriterion("finish_date is not null");
            return (Criteria) this;
        }

        public Criteria andFinishDateEqualTo(Date value) {
            addCriterionForJDBCDate("finish_date =", value, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateNotEqualTo(Date value) {
            addCriterionForJDBCDate("finish_date <>", value, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateGreaterThan(Date value) {
            addCriterionForJDBCDate("finish_date >", value, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("finish_date >=", value, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateLessThan(Date value) {
            addCriterionForJDBCDate("finish_date <", value, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("finish_date <=", value, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateIn(List<Date> values) {
            addCriterionForJDBCDate("finish_date in", values, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateNotIn(List<Date> values) {
            addCriterionForJDBCDate("finish_date not in", values, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("finish_date between", value1, value2, "finishDate");
            return (Criteria) this;
        }

        public Criteria andFinishDateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("finish_date not between", value1, value2, "finishDate");
            return (Criteria) this;
        }

        public Criteria andPayIntFreqIsNull() {
            addCriterion("pay_int_freq is null");
            return (Criteria) this;
        }

        public Criteria andPayIntFreqIsNotNull() {
            addCriterion("pay_int_freq is not null");
            return (Criteria) this;
        }

        public Criteria andPayIntFreqEqualTo(String value) {
            addCriterion("pay_int_freq =", value, "payIntFreq");
            return (Criteria) this;
        }

        public Criteria andPayIntFreqNotEqualTo(String value) {
            addCriterion("pay_int_freq <>", value, "payIntFreq");
            return (Criteria) this;
        }

        public Criteria andPayIntFreqGreaterThan(String value) {
            addCriterion("pay_int_freq >", value, "payIntFreq");
            return (Criteria) this;
        }

        public Criteria andPayIntFreqGreaterThanOrEqualTo(String value) {
            addCriterion("pay_int_freq >=", value, "payIntFreq");
            return (Criteria) this;
        }

        public Criteria andPayIntFreqLessThan(String value) {
            addCriterion("pay_int_freq <", value, "payIntFreq");
            return (Criteria) this;
        }

        public Criteria andPayIntFreqLessThanOrEqualTo(String value) {
            addCriterion("pay_int_freq <=", value, "payIntFreq");
            return (Criteria) this;
        }

        public Criteria andPayIntFreqLike(String value) {
            addCriterion("pay_int_freq like", value, "payIntFreq");
            return (Criteria) this;
        }

        public Criteria andPayIntFreqNotLike(String value) {
            addCriterion("pay_int_freq not like", value, "payIntFreq");
            return (Criteria) this;
        }

        public Criteria andPayIntFreqIn(List<String> values) {
            addCriterion("pay_int_freq in", values, "payIntFreq");
            return (Criteria) this;
        }

        public Criteria andPayIntFreqNotIn(List<String> values) {
            addCriterion("pay_int_freq not in", values, "payIntFreq");
            return (Criteria) this;
        }

        public Criteria andPayIntFreqBetween(String value1, String value2) {
            addCriterion("pay_int_freq between", value1, value2, "payIntFreq");
            return (Criteria) this;
        }

        public Criteria andPayIntFreqNotBetween(String value1, String value2) {
            addCriterion("pay_int_freq not between", value1, value2, "payIntFreq");
            return (Criteria) this;
        }

        public Criteria andIntCalcTypeeIsNull() {
            addCriterion("int_calc_typee is null");
            return (Criteria) this;
        }

        public Criteria andIntCalcTypeeIsNotNull() {
            addCriterion("int_calc_typee is not null");
            return (Criteria) this;
        }

        public Criteria andIntCalcTypeeEqualTo(String value) {
            addCriterion("int_calc_typee =", value, "intCalcTypee");
            return (Criteria) this;
        }

        public Criteria andIntCalcTypeeNotEqualTo(String value) {
            addCriterion("int_calc_typee <>", value, "intCalcTypee");
            return (Criteria) this;
        }

        public Criteria andIntCalcTypeeGreaterThan(String value) {
            addCriterion("int_calc_typee >", value, "intCalcTypee");
            return (Criteria) this;
        }

        public Criteria andIntCalcTypeeGreaterThanOrEqualTo(String value) {
            addCriterion("int_calc_typee >=", value, "intCalcTypee");
            return (Criteria) this;
        }

        public Criteria andIntCalcTypeeLessThan(String value) {
            addCriterion("int_calc_typee <", value, "intCalcTypee");
            return (Criteria) this;
        }

        public Criteria andIntCalcTypeeLessThanOrEqualTo(String value) {
            addCriterion("int_calc_typee <=", value, "intCalcTypee");
            return (Criteria) this;
        }

        public Criteria andIntCalcTypeeLike(String value) {
            addCriterion("int_calc_typee like", value, "intCalcTypee");
            return (Criteria) this;
        }

        public Criteria andIntCalcTypeeNotLike(String value) {
            addCriterion("int_calc_typee not like", value, "intCalcTypee");
            return (Criteria) this;
        }

        public Criteria andIntCalcTypeeIn(List<String> values) {
            addCriterion("int_calc_typee in", values, "intCalcTypee");
            return (Criteria) this;
        }

        public Criteria andIntCalcTypeeNotIn(List<String> values) {
            addCriterion("int_calc_typee not in", values, "intCalcTypee");
            return (Criteria) this;
        }

        public Criteria andIntCalcTypeeBetween(String value1, String value2) {
            addCriterion("int_calc_typee between", value1, value2, "intCalcTypee");
            return (Criteria) this;
        }

        public Criteria andIntCalcTypeeNotBetween(String value1, String value2) {
            addCriterion("int_calc_typee not between", value1, value2, "intCalcTypee");
            return (Criteria) this;
        }

        public Criteria andStatedRateIsNull() {
            addCriterion("stated_rate is null");
            return (Criteria) this;
        }

        public Criteria andStatedRateIsNotNull() {
            addCriterion("stated_rate is not null");
            return (Criteria) this;
        }

        public Criteria andStatedRateEqualTo(BigDecimal value) {
            addCriterion("stated_rate =", value, "statedRate");
            return (Criteria) this;
        }

        public Criteria andStatedRateNotEqualTo(BigDecimal value) {
            addCriterion("stated_rate <>", value, "statedRate");
            return (Criteria) this;
        }

        public Criteria andStatedRateGreaterThan(BigDecimal value) {
            addCriterion("stated_rate >", value, "statedRate");
            return (Criteria) this;
        }

        public Criteria andStatedRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("stated_rate >=", value, "statedRate");
            return (Criteria) this;
        }

        public Criteria andStatedRateLessThan(BigDecimal value) {
            addCriterion("stated_rate <", value, "statedRate");
            return (Criteria) this;
        }

        public Criteria andStatedRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("stated_rate <=", value, "statedRate");
            return (Criteria) this;
        }

        public Criteria andStatedRateIn(List<BigDecimal> values) {
            addCriterion("stated_rate in", values, "statedRate");
            return (Criteria) this;
        }

        public Criteria andStatedRateNotIn(List<BigDecimal> values) {
            addCriterion("stated_rate not in", values, "statedRate");
            return (Criteria) this;
        }

        public Criteria andStatedRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("stated_rate between", value1, value2, "statedRate");
            return (Criteria) this;
        }

        public Criteria andStatedRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("stated_rate not between", value1, value2, "statedRate");
            return (Criteria) this;
        }

        public Criteria andBondUnitIsNull() {
            addCriterion("bond_unit is null");
            return (Criteria) this;
        }

        public Criteria andBondUnitIsNotNull() {
            addCriterion("bond_unit is not null");
            return (Criteria) this;
        }

        public Criteria andBondUnitEqualTo(Long value) {
            addCriterion("bond_unit =", value, "bondUnit");
            return (Criteria) this;
        }

        public Criteria andBondUnitNotEqualTo(Long value) {
            addCriterion("bond_unit <>", value, "bondUnit");
            return (Criteria) this;
        }

        public Criteria andBondUnitGreaterThan(Long value) {
            addCriterion("bond_unit >", value, "bondUnit");
            return (Criteria) this;
        }

        public Criteria andBondUnitGreaterThanOrEqualTo(Long value) {
            addCriterion("bond_unit >=", value, "bondUnit");
            return (Criteria) this;
        }

        public Criteria andBondUnitLessThan(Long value) {
            addCriterion("bond_unit <", value, "bondUnit");
            return (Criteria) this;
        }

        public Criteria andBondUnitLessThanOrEqualTo(Long value) {
            addCriterion("bond_unit <=", value, "bondUnit");
            return (Criteria) this;
        }

        public Criteria andBondUnitIn(List<Long> values) {
            addCriterion("bond_unit in", values, "bondUnit");
            return (Criteria) this;
        }

        public Criteria andBondUnitNotIn(List<Long> values) {
            addCriterion("bond_unit not in", values, "bondUnit");
            return (Criteria) this;
        }

        public Criteria andBondUnitBetween(Long value1, Long value2) {
            addCriterion("bond_unit between", value1, value2, "bondUnit");
            return (Criteria) this;
        }

        public Criteria andBondUnitNotBetween(Long value1, Long value2) {
            addCriterion("bond_unit not between", value1, value2, "bondUnit");
            return (Criteria) this;
        }

        public Criteria andCashOutRateIsNull() {
            addCriterion("cash_out_rate is null");
            return (Criteria) this;
        }

        public Criteria andCashOutRateIsNotNull() {
            addCriterion("cash_out_rate is not null");
            return (Criteria) this;
        }

        public Criteria andCashOutRateEqualTo(BigDecimal value) {
            addCriterion("cash_out_rate =", value, "cashOutRate");
            return (Criteria) this;
        }

        public Criteria andCashOutRateNotEqualTo(BigDecimal value) {
            addCriterion("cash_out_rate <>", value, "cashOutRate");
            return (Criteria) this;
        }

        public Criteria andCashOutRateGreaterThan(BigDecimal value) {
            addCriterion("cash_out_rate >", value, "cashOutRate");
            return (Criteria) this;
        }

        public Criteria andCashOutRateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("cash_out_rate >=", value, "cashOutRate");
            return (Criteria) this;
        }

        public Criteria andCashOutRateLessThan(BigDecimal value) {
            addCriterion("cash_out_rate <", value, "cashOutRate");
            return (Criteria) this;
        }

        public Criteria andCashOutRateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("cash_out_rate <=", value, "cashOutRate");
            return (Criteria) this;
        }

        public Criteria andCashOutRateIn(List<BigDecimal> values) {
            addCriterion("cash_out_rate in", values, "cashOutRate");
            return (Criteria) this;
        }

        public Criteria andCashOutRateNotIn(List<BigDecimal> values) {
            addCriterion("cash_out_rate not in", values, "cashOutRate");
            return (Criteria) this;
        }

        public Criteria andCashOutRateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cash_out_rate between", value1, value2, "cashOutRate");
            return (Criteria) this;
        }

        public Criteria andCashOutRateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("cash_out_rate not between", value1, value2, "cashOutRate");
            return (Criteria) this;
        }

        public Criteria andBasicQuotaIsNull() {
            addCriterion("basic_quota is null");
            return (Criteria) this;
        }

        public Criteria andBasicQuotaIsNotNull() {
            addCriterion("basic_quota is not null");
            return (Criteria) this;
        }

        public Criteria andBasicQuotaEqualTo(Long value) {
            addCriterion("basic_quota =", value, "basicQuota");
            return (Criteria) this;
        }

        public Criteria andBasicQuotaNotEqualTo(Long value) {
            addCriterion("basic_quota <>", value, "basicQuota");
            return (Criteria) this;
        }

        public Criteria andBasicQuotaGreaterThan(Long value) {
            addCriterion("basic_quota >", value, "basicQuota");
            return (Criteria) this;
        }

        public Criteria andBasicQuotaGreaterThanOrEqualTo(Long value) {
            addCriterion("basic_quota >=", value, "basicQuota");
            return (Criteria) this;
        }

        public Criteria andBasicQuotaLessThan(Long value) {
            addCriterion("basic_quota <", value, "basicQuota");
            return (Criteria) this;
        }

        public Criteria andBasicQuotaLessThanOrEqualTo(Long value) {
            addCriterion("basic_quota <=", value, "basicQuota");
            return (Criteria) this;
        }

        public Criteria andBasicQuotaIn(List<Long> values) {
            addCriterion("basic_quota in", values, "basicQuota");
            return (Criteria) this;
        }

        public Criteria andBasicQuotaNotIn(List<Long> values) {
            addCriterion("basic_quota not in", values, "basicQuota");
            return (Criteria) this;
        }

        public Criteria andBasicQuotaBetween(Long value1, Long value2) {
            addCriterion("basic_quota between", value1, value2, "basicQuota");
            return (Criteria) this;
        }

        public Criteria andBasicQuotaNotBetween(Long value1, Long value2) {
            addCriterion("basic_quota not between", value1, value2, "basicQuota");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNull() {
            addCriterion("product_id is null");
            return (Criteria) this;
        }

        public Criteria andProductIdIsNotNull() {
            addCriterion("product_id is not null");
            return (Criteria) this;
        }

        public Criteria andProductIdEqualTo(String value) {
            addCriterion("product_id =", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotEqualTo(String value) {
            addCriterion("product_id <>", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThan(String value) {
            addCriterion("product_id >", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdGreaterThanOrEqualTo(String value) {
            addCriterion("product_id >=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThan(String value) {
            addCriterion("product_id <", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLessThanOrEqualTo(String value) {
            addCriterion("product_id <=", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdLike(String value) {
            addCriterion("product_id like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotLike(String value) {
            addCriterion("product_id not like", value, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdIn(List<String> values) {
            addCriterion("product_id in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotIn(List<String> values) {
            addCriterion("product_id not in", values, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdBetween(String value1, String value2) {
            addCriterion("product_id between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andProductIdNotBetween(String value1, String value2) {
            addCriterion("product_id not between", value1, value2, "productId");
            return (Criteria) this;
        }

        public Criteria andLiquidationStatusIsNull() {
            addCriterion("liquidation_status is null");
            return (Criteria) this;
        }

        public Criteria andLiquidationStatusIsNotNull() {
            addCriterion("liquidation_status is not null");
            return (Criteria) this;
        }

        public Criteria andLiquidationStatusEqualTo(String value) {
            addCriterion("liquidation_status =", value, "liquidationStatus");
            return (Criteria) this;
        }

        public Criteria andLiquidationStatusNotEqualTo(String value) {
            addCriterion("liquidation_status <>", value, "liquidationStatus");
            return (Criteria) this;
        }

        public Criteria andLiquidationStatusGreaterThan(String value) {
            addCriterion("liquidation_status >", value, "liquidationStatus");
            return (Criteria) this;
        }

        public Criteria andLiquidationStatusGreaterThanOrEqualTo(String value) {
            addCriterion("liquidation_status >=", value, "liquidationStatus");
            return (Criteria) this;
        }

        public Criteria andLiquidationStatusLessThan(String value) {
            addCriterion("liquidation_status <", value, "liquidationStatus");
            return (Criteria) this;
        }

        public Criteria andLiquidationStatusLessThanOrEqualTo(String value) {
            addCriterion("liquidation_status <=", value, "liquidationStatus");
            return (Criteria) this;
        }

        public Criteria andLiquidationStatusLike(String value) {
            addCriterion("liquidation_status like", value, "liquidationStatus");
            return (Criteria) this;
        }

        public Criteria andLiquidationStatusNotLike(String value) {
            addCriterion("liquidation_status not like", value, "liquidationStatus");
            return (Criteria) this;
        }

        public Criteria andLiquidationStatusIn(List<String> values) {
            addCriterion("liquidation_status in", values, "liquidationStatus");
            return (Criteria) this;
        }

        public Criteria andLiquidationStatusNotIn(List<String> values) {
            addCriterion("liquidation_status not in", values, "liquidationStatus");
            return (Criteria) this;
        }

        public Criteria andLiquidationStatusBetween(String value1, String value2) {
            addCriterion("liquidation_status between", value1, value2, "liquidationStatus");
            return (Criteria) this;
        }

        public Criteria andLiquidationStatusNotBetween(String value1, String value2) {
            addCriterion("liquidation_status not between", value1, value2, "liquidationStatus");
            return (Criteria) this;
        }

        public Criteria andProductCodeIsNull() {
            addCriterion("product_code is null");
            return (Criteria) this;
        }

        public Criteria andProductCodeIsNotNull() {
            addCriterion("product_code is not null");
            return (Criteria) this;
        }

        public Criteria andProductCodeEqualTo(String value) {
            addCriterion("product_code =", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotEqualTo(String value) {
            addCriterion("product_code <>", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeGreaterThan(String value) {
            addCriterion("product_code >", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeGreaterThanOrEqualTo(String value) {
            addCriterion("product_code >=", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLessThan(String value) {
            addCriterion("product_code <", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLessThanOrEqualTo(String value) {
            addCriterion("product_code <=", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeLike(String value) {
            addCriterion("product_code like", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotLike(String value) {
            addCriterion("product_code not like", value, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeIn(List<String> values) {
            addCriterion("product_code in", values, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotIn(List<String> values) {
            addCriterion("product_code not in", values, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeBetween(String value1, String value2) {
            addCriterion("product_code between", value1, value2, "productCode");
            return (Criteria) this;
        }

        public Criteria andProductCodeNotBetween(String value1, String value2) {
            addCriterion("product_code not between", value1, value2, "productCode");
            return (Criteria) this;
        }

        public Criteria andBondNumIsNull() {
            addCriterion("bond_num is null");
            return (Criteria) this;
        }

        public Criteria andBondNumIsNotNull() {
            addCriterion("bond_num is not null");
            return (Criteria) this;
        }

        public Criteria andBondNumEqualTo(String value) {
            addCriterion("bond_num =", value, "bondNum");
            return (Criteria) this;
        }

        public Criteria andBondNumNotEqualTo(String value) {
            addCriterion("bond_num <>", value, "bondNum");
            return (Criteria) this;
        }

        public Criteria andBondNumGreaterThan(String value) {
            addCriterion("bond_num >", value, "bondNum");
            return (Criteria) this;
        }

        public Criteria andBondNumGreaterThanOrEqualTo(String value) {
            addCriterion("bond_num >=", value, "bondNum");
            return (Criteria) this;
        }

        public Criteria andBondNumLessThan(String value) {
            addCriterion("bond_num <", value, "bondNum");
            return (Criteria) this;
        }

        public Criteria andBondNumLessThanOrEqualTo(String value) {
            addCriterion("bond_num <=", value, "bondNum");
            return (Criteria) this;
        }

        public Criteria andBondNumLike(String value) {
            addCriterion("bond_num like", value, "bondNum");
            return (Criteria) this;
        }

        public Criteria andBondNumNotLike(String value) {
            addCriterion("bond_num not like", value, "bondNum");
            return (Criteria) this;
        }

        public Criteria andBondNumIn(List<String> values) {
            addCriterion("bond_num in", values, "bondNum");
            return (Criteria) this;
        }

        public Criteria andBondNumNotIn(List<String> values) {
            addCriterion("bond_num not in", values, "bondNum");
            return (Criteria) this;
        }

        public Criteria andBondNumBetween(String value1, String value2) {
            addCriterion("bond_num between", value1, value2, "bondNum");
            return (Criteria) this;
        }

        public Criteria andBondNumNotBetween(String value1, String value2) {
            addCriterion("bond_num not between", value1, value2, "bondNum");
            return (Criteria) this;
        }

        public Criteria andBondPeriodIsNull() {
            addCriterion("bond_period is null");
            return (Criteria) this;
        }

        public Criteria andBondPeriodIsNotNull() {
            addCriterion("bond_period is not null");
            return (Criteria) this;
        }

        public Criteria andBondPeriodEqualTo(String value) {
            addCriterion("bond_period =", value, "bondPeriod");
            return (Criteria) this;
        }

        public Criteria andBondPeriodNotEqualTo(String value) {
            addCriterion("bond_period <>", value, "bondPeriod");
            return (Criteria) this;
        }

        public Criteria andBondPeriodGreaterThan(String value) {
            addCriterion("bond_period >", value, "bondPeriod");
            return (Criteria) this;
        }

        public Criteria andBondPeriodGreaterThanOrEqualTo(String value) {
            addCriterion("bond_period >=", value, "bondPeriod");
            return (Criteria) this;
        }

        public Criteria andBondPeriodLessThan(String value) {
            addCriterion("bond_period <", value, "bondPeriod");
            return (Criteria) this;
        }

        public Criteria andBondPeriodLessThanOrEqualTo(String value) {
            addCriterion("bond_period <=", value, "bondPeriod");
            return (Criteria) this;
        }

        public Criteria andBondPeriodLike(String value) {
            addCriterion("bond_period like", value, "bondPeriod");
            return (Criteria) this;
        }

        public Criteria andBondPeriodNotLike(String value) {
            addCriterion("bond_period not like", value, "bondPeriod");
            return (Criteria) this;
        }

        public Criteria andBondPeriodIn(List<String> values) {
            addCriterion("bond_period in", values, "bondPeriod");
            return (Criteria) this;
        }

        public Criteria andBondPeriodNotIn(List<String> values) {
            addCriterion("bond_period not in", values, "bondPeriod");
            return (Criteria) this;
        }

        public Criteria andBondPeriodBetween(String value1, String value2) {
            addCriterion("bond_period between", value1, value2, "bondPeriod");
            return (Criteria) this;
        }

        public Criteria andBondPeriodNotBetween(String value1, String value2) {
            addCriterion("bond_period not between", value1, value2, "bondPeriod");
            return (Criteria) this;
        }

        public Criteria andCashStartDateIsNull() {
            addCriterion("cash_start_date is null");
            return (Criteria) this;
        }

        public Criteria andCashStartDateIsNotNull() {
            addCriterion("cash_start_date is not null");
            return (Criteria) this;
        }

        public Criteria andCashStartDateEqualTo(String value) {
            addCriterion("cash_start_date =", value, "cashStartDate");
            return (Criteria) this;
        }

        public Criteria andCashStartDateNotEqualTo(String value) {
            addCriterion("cash_start_date <>", value, "cashStartDate");
            return (Criteria) this;
        }

        public Criteria andCashStartDateGreaterThan(String value) {
            addCriterion("cash_start_date >", value, "cashStartDate");
            return (Criteria) this;
        }

        public Criteria andCashStartDateGreaterThanOrEqualTo(String value) {
            addCriterion("cash_start_date >=", value, "cashStartDate");
            return (Criteria) this;
        }

        public Criteria andCashStartDateLessThan(String value) {
            addCriterion("cash_start_date <", value, "cashStartDate");
            return (Criteria) this;
        }

        public Criteria andCashStartDateLessThanOrEqualTo(String value) {
            addCriterion("cash_start_date <=", value, "cashStartDate");
            return (Criteria) this;
        }

        public Criteria andCashStartDateLike(String value) {
            addCriterion("cash_start_date like", value, "cashStartDate");
            return (Criteria) this;
        }

        public Criteria andCashStartDateNotLike(String value) {
            addCriterion("cash_start_date not like", value, "cashStartDate");
            return (Criteria) this;
        }

        public Criteria andCashStartDateIn(List<String> values) {
            addCriterion("cash_start_date in", values, "cashStartDate");
            return (Criteria) this;
        }

        public Criteria andCashStartDateNotIn(List<String> values) {
            addCriterion("cash_start_date not in", values, "cashStartDate");
            return (Criteria) this;
        }

        public Criteria andCashStartDateBetween(String value1, String value2) {
            addCriterion("cash_start_date between", value1, value2, "cashStartDate");
            return (Criteria) this;
        }

        public Criteria andCashStartDateNotBetween(String value1, String value2) {
            addCriterion("cash_start_date not between", value1, value2, "cashStartDate");
            return (Criteria) this;
        }

        public Criteria andCashEndDateIsNull() {
            addCriterion("cash_end_date is null");
            return (Criteria) this;
        }

        public Criteria andCashEndDateIsNotNull() {
            addCriterion("cash_end_date is not null");
            return (Criteria) this;
        }

        public Criteria andCashEndDateEqualTo(String value) {
            addCriterion("cash_end_date =", value, "cashEndDate");
            return (Criteria) this;
        }

        public Criteria andCashEndDateNotEqualTo(String value) {
            addCriterion("cash_end_date <>", value, "cashEndDate");
            return (Criteria) this;
        }

        public Criteria andCashEndDateGreaterThan(String value) {
            addCriterion("cash_end_date >", value, "cashEndDate");
            return (Criteria) this;
        }

        public Criteria andCashEndDateGreaterThanOrEqualTo(String value) {
            addCriterion("cash_end_date >=", value, "cashEndDate");
            return (Criteria) this;
        }

        public Criteria andCashEndDateLessThan(String value) {
            addCriterion("cash_end_date <", value, "cashEndDate");
            return (Criteria) this;
        }

        public Criteria andCashEndDateLessThanOrEqualTo(String value) {
            addCriterion("cash_end_date <=", value, "cashEndDate");
            return (Criteria) this;
        }

        public Criteria andCashEndDateLike(String value) {
            addCriterion("cash_end_date like", value, "cashEndDate");
            return (Criteria) this;
        }

        public Criteria andCashEndDateNotLike(String value) {
            addCriterion("cash_end_date not like", value, "cashEndDate");
            return (Criteria) this;
        }

        public Criteria andCashEndDateIn(List<String> values) {
            addCriterion("cash_end_date in", values, "cashEndDate");
            return (Criteria) this;
        }

        public Criteria andCashEndDateNotIn(List<String> values) {
            addCriterion("cash_end_date not in", values, "cashEndDate");
            return (Criteria) this;
        }

        public Criteria andCashEndDateBetween(String value1, String value2) {
            addCriterion("cash_end_date between", value1, value2, "cashEndDate");
            return (Criteria) this;
        }

        public Criteria andCashEndDateNotBetween(String value1, String value2) {
            addCriterion("cash_end_date not between", value1, value2, "cashEndDate");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bond_info
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 10 22:27:27 CST 2023
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}