### queryKeAcFacility  返回单一对象
POST http://localhost:8080/bond/channel/inventory/query
Content-Type: application/json

{
    "product_Code": "100111",
    "bond_Code":"BOND001"
}

### queryKeAcFacility  返回列表
POST http://localhost:8080/bond/channel/inventory/queryAll
Content-Type: application/json

{
    "product_Code": "100111",
    "bond_Code":"BOND001",
    "view_index":"3",
    "view_size":"4"
}
### setKeepAccount 债券注册，返回结果
POST http://localhost:8080/bond/product/register
Content-Type: application/json

{
  "productId": "12345",
  "product_code": "P001",
  "bond_code": "B001",
  "xfx_flag": "Y",
  "xfx_rateOfIncome": "5.5%",
  "original_bond_code": "OB001",
  "bond_variety": "Government",
  "bond_name": "Government Bond",
  "bond_short_name": "GovBond",
  "local_bond_sales_area": "USA",
  "currency_code": "USD",
  "bond_issue_year": "2024",
  "bond_issue_term": "10 years",
  "bond_time": "10:00",
  "current_par_interestrate": "3.0%",
  "float_par_interrate_norm": "0.5%",
  "float_par_interbalance": "1000",
  "calinterest_mode": "Fixed",
  "calinterest_norm": "Standard",
  "pay_interest_frequency": "Annual",
  "bond_issue_uplimit": "1000000",
  "bond_issue_lowlimit": "1000",
  "bond_change_unit": "10",
  "issue_date": "2024-05-01",
  "begin_calinterest_date": "2024-06-01",
  "initial_sepsell_date": "2024-07-01",
  "end_sepsell_date": "2024-08-01",
  "maket_circulating_date": "2024-09-01",
  "cash_date": "2024-10-01",
  "befpay_altertrust_stopdays": "10",
  "befpay_bond_registerdays": "15",
  "close_transfer_days": "5",
  "consign_quantum": "500",
  "issue_price": "100",
  "befCashDay_OutRequest_stopdays": "3",
  "calinterest_norm": "Standard"
}

### quotation/push 返回结果
POST http://localhost:8080/api/quotation/push
Content-Type: application/json

{
  "transNo": "T2024012002",
  "bondCode": "BOND001",
  "priceSource": "1",
  "priceDecimal": 100.6,
  "quotaTime": "2024-01-20T15:00:00"
}


