package com.example.demo.mapper;

import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import com.example.demo.model.BondInfo;
import com.example.demo.model.BondInfoExample;

@Mapper
public interface BondInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    long countByExample(BondInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    int deleteByExample(BondInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    int insert(BondInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    int insertSelective(BondInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    List<BondInfo> selectByExampleWithBLOBs(BondInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    List<BondInfo> selectByExample(BondInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    BondInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    int updateByExampleSelective(@Param("record") BondInfo record, @Param("example") BondInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    int updateByExampleWithBLOBs(@Param("record") BondInfo record, @Param("example") BondInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    int updateByExample(@Param("record") BondInfo record, @Param("example") BondInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    int updateByPrimaryKeySelective(BondInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    int updateByPrimaryKeyWithBLOBs(BondInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bond_info
     *
     * @mbg.generated Mon Jul 10 22:27:27 CST 2023
     */
    int updateByPrimaryKey(BondInfo record);
}